" vi
set tabstop=8 shiftwidth=2
set autoindent
set showmatch matchtime=1
" map \ :tag 

" vim and nvi
set tildeop

" vim
set encoding=utf-8
set nocompatible
set expandtab smarttab softtabstop=2 shiftround
set ignorecase smartcase
set suffixes=.o,.info,.swp,.obj
set noshowmode noruler
set modeline modelines=5
set matchpairs+=<:>,‹:›,«:»,‘:’,“:”
set mouse=
set cursorline
set shortmess=filnrxoOtTI
set foldmethod=syntax foldlevel=1 nofoldenable
set nojoinspaces
set formatoptions-=ol
set formatoptions+=j1
set timeout ttimeout timeoutlen=3000 ttimeoutlen=100
set fileencodings=ucs-bom,utf-8,default
set breakindent
set completeopt=menu,preview,longest
autocmd! CompleteDone * if pumvisible() == 0 | pclose | endif

if has('cscope')
  set cscopetagorder=1 cscopepathcomp=3
endif

" neovim corrections
set noautoread nohidden nohlsearch noincsearch
set laststatus=1
if has('nvim')
  set inccommand=
endif

map <Home>  1G
map <kHome> 1G
map <End>   G
map <kEnd>  G
map <special> <silent> <C--> :set cursorline!<CR>
map <special> <silent> <C-\> :set cursorcolumn!<CR>
nmap <special> <M-]>   :tag<Space>

function OnVimResized()
  if &columns >= 82
    set signcolumn=yes
  else
    set signcolumn=auto
  endif
endfunction
call OnVimResized()
autocmd! VimResized * call OnVimResized()

let g:pandoc#syntax#conceal#cchar_overrides = {"atx":"#"}
let g:xml_syntax_folding = 1
let c_space_errors = 2


if has('nvim')
  runtime neo-packages.vim
else
  runtime vim-packages.vim
endif

" See also ~/.vim/after/plugin/vimrc.vim
